#!groovy
podTemplate(
  label: "skopeo-pod",
  cloud: "openshift",
  inheritFrom: "maven",
  containers: [
    containerTemplate(
      name: "jnlp",
      image: "docker-registry.default.svc:5000/7af9-jenkins/jenkins-agent-appdev",
      resourceRequestMemory: "1Gi",
      resourceLimitMemory: "2Gi",
      resourceRequestCpu: "1",
      resourceLimitCpu: "2"
    )
  ]
) {
  node('skopeo-pod') {
    // Define Maven Command to point to the correct
    // settings for our Nexus installation
    def mvnCmd = "mvn -s ../nexus_settings.xml"

    // Checkout Source Code.
    stage('Checkout Source') {
      sh("oc whoami")
      checkout scm
    }

    // Build the Tasks Service
    dir('openshift-tasks') {
      // The following variables need to be defined at the top level
      // and not inside the scope of a stage - otherwise they would not
      // be accessible from other stages.
      // Extract version from the pom.xml
      def version = getVersionFromPom("pom.xml")
      def devTag  = "${version}-${BUILD_NUMBER}"
      def prodTag = "${version}"


      // Using Maven build the war file
      // Do not run tests in this step
      stage('Build war') {
        echo "Building version ${devTag}"
        sh "${mvnCmd} clean package -DskipTests=true"
      }

      // TBD: The next two stages should run in parallel

      // Using Maven run the unit tests
      stage('Unit Tests') {
        echo "Running Unit Tests"
        sh "${mvnCmd} test"
      }

      // Using Maven to call SonarQube for Code Analysis
      stage('Code Analysis') {
        echo "Running Code Analysis"
        sh "${mvnCmd} sonar:sonar -Dsonar.host.url=http://sonarqube.gpte-hw-cicd.svc.cluster.local:9000 -Dsonar.projectName=${JOB_BASE_NAME}-${devTag}"      
      }

      // Publish the built war file to Nexus
      stage('Publish to Nexus') {
        echo "Publish to Nexus"
        sh "${mvnCmd} clean deploy -e -DskipTests=true -DaltDeploymentRepository=nexus::default::http://nexus3.gpte-hw-cicd.svc.cluster.local:8081/repository/releases"
      }

      // Build the OpenShift Image in OpenShift and tag it.
      stage('Build and Tag OpenShift Image') {
        echo "Building OpenShift container image tasks:${devTag}"
        sh('oc start-build tasks --follow --from-file=./target/openshift-tasks.war -n 7af9-tasks-dev')
        openshiftTag alias: 'false', destStream: 'tasks', destTag: devTag, destinationNamespace: '7af9-tasks-dev', namespace: '7af9-tasks-dev', srcStream: 'tasks', srcTag: 'latest', verbose: 'false'
      }

      // Deploy the built image to the Development Environment.
      stage('Deploy to Dev') {
        echo "Deploying container image to Development Project"
        sh "oc set image dc/tasks tasks=docker-registry.default.svc:5000/7af9-tasks-dev/tasks:${devTag} -n 7af9-tasks-dev"
        sh "oc delete configmap tasks-config -n 7af9-tasks-dev --ignore-not-found=true"
        sh "oc create configmap tasks-config --from-literal=VERSION='${devTag} (tasks-dev)' --from-file=./configuration/application-users.properties --from-file=./configuration/application-roles.properties -n 7af9-tasks-dev"

        openshiftDeploy depCfg: 'tasks', namespace: '7af9-tasks-dev', verbose: 'false', waitTime: '', waitUnit: 'sec'
        openshiftVerifyDeployment depCfg: 'tasks', namespace: '7af9-tasks-dev', replicaCount: '1', verbose: 'false', verifyReplicaCount: 'false', waitTime: '', waitUnit: 'sec'
        openshiftVerifyService namespace: '7af9-tasks-dev', svcName: 'tasks', verbose: 'false'
      }

      // Copy Image to Nexus container registry
      stage('Copy Image to Nexus container registry') {
        echo "Copy image to Nexus container registry"
        sh "skopeo copy --src-tls-verify=false --dest-tls-verify=false --src-creds openshift:\$(oc whoami -t) --dest-creds admin:redhat docker://docker-registry.default.svc.cluster.local:5000/7af9-tasks-dev/tasks:${devTag} docker://nexus-registry.gpte-hw-cicd.svc.cluster.local:5000/tasks:${devTag}"
        openshiftTag alias: 'false', destStream: 'tasks', destTag: prodTag, destinationNamespace: '7af9-tasks-dev', namespace: '7af9-tasks-dev', srcStream: 'tasks', srcTag: devTag, verbose: 'false'
      }

      // Blue/Green Deployment into Production
      // -------------------------------------
      def destApp   = "tasks-green"
      def activeApp = ""

      stage('Blue/Green Production Deployment') {
         activeApp = sh(returnStdout: true, script: "oc get route tasks -n 7af9-tasks-prod -o jsonpath='{ .spec.to.name }'").trim()
      
           if (activeApp == "tasks-green") {
            destApp = "tasks-blue"
          }
          if (activeApp == "tasks-blue") {
            destApp = "tasks-green"
          }

          echo "Active Application:      " + activeApp
          echo "Destination Application: " + destApp
        
          sh "oc set image dc/${destApp} ${destApp}=docker-registry.default.svc:5000/7af9-tasks-dev/tasks:${prodTag} -n 7af9-tasks-prod"
        
          sh "oc delete configmap ${destApp}-config -n 7af9-tasks-prod --ignore-not-found=true"
          sh "oc create configmap ${destApp}-config --from-literal=VERSION='${prodTag} (${destApp})' --from-file=./configuration/application-users.properties --from-file=./configuration/application-roles.properties -n 7af9-tasks-prod"
        
          sh "oc set env dc/${destApp} VERSION='${prodTag} (${destApp})' -n 7af9-tasks-prod" 
          
          openshiftDeploy depCfg: destApp, namespace: '7af9-tasks-prod', verbose: 'true', waitTime: '', waitUnit: 'sec'
          openshiftVerifyDeployment depCfg: destApp, namespace: '7af9-tasks-prod', replicaCount: '1', verbose: 'false', verifyReplicaCount: 'true', waitTime: '', waitUnit: 'sec'
          openshiftVerifyService namespace: '7af9-tasks-prod', svcName: destApp, verbose: 'true'
      }

      stage('Switch over to new Version') {
        echo "Switching Production application to ${destApp}."
        // TBD: Execute switch
      }
    }
  }
}

// Convenience Functions to read version from the pom.xml
// Do not change anything below this line.
// --------------------------------------------------------
def getVersionFromPom(pom) {
  def matcher = readFile(pom) =~ '<version>(.+)</version>'
  matcher ? matcher[0][1] : null
}